### ISSUE TITLE
Identifier uniqueness checks

### ISSUE THREAD

**Issue by lgs85** [Open-Telecoms-Data/lib-cove-ofds#1]
We need to set up an instance of [CoVE](https://cove.opendataservices.coop/) for conversion, validation and exploration of OFDS data.

Let's use this issue to start thinking about any additional checks that we might like to put into the first release.

**Comment by odscjames** [comment]
> links.end must match the .id of a link in the links array. 

That's a typo right?

**Comment by odscjames** [comment]
How about:

All nodes must be used in a link?

**Comment by duncandewhurst** [comment]
Thanks for flagging the typos. I've corrected them. Thankfully, they existed only in this issue and not in the standard itself.

> All nodes must be used in a link?

It's not a normative rule but it could be a useful 'sense check' with a message like:

> Your data contains nodes that are not referenced by any links. You should check that this is not the result of an error in your mapping or data pipeline.

**Comment by odscjames** [comment]
relatedResources and paging - does that change how any checks are defined? Should we be loading more resources?

> It's not a normative rule but it could be a useful 'sense check' with a message like:

Yeah, we can display different errors with different levels of severity in the UI.

**Comment by odscjames** [comment]
> relatedResources

talked to @lgs85 - for first pass, we just won't run some checks if any relatedResources are present. would be nice to indicate in UI this has happened.

**Comment by odscjames** [comment]
> PhaseReference.id must match the .id of a phase in the phases array (applies to nodes.phase, links.phase, contracts.phase)
> PhaseReference.name must match the .name of the phase in the phases array whose .id matches the .id of this phase reference (applies to nodes.phase, links.phase, contracts.phase)

I assume this is meant to mean contracts.relatedPhases

**Comment by duncandewhurst** [comment]
> > PhaseReference.id must match the .id of a phase in the phases array (applies to nodes.phase, links.phase, contracts.phase)
> > PhaseReference.name must match the .name of the phase in the phases array whose .id matches the .id of this phase reference (applies to nodes.phase, links.phase, contracts.phase)
> 
> I assume this is meant to mean contracts.relatedPhases

Yep, that's correct.

> Name is optional, so how strict are we being here?

If `PhaseReference.name` isn't present, we can just skip the check.

**Comment by lgs85** [comment]
Based on [this comment](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/issues/54#issuecomment-1280840403), could we look for fields with American spellings and include a friendly error message stating that the standard uses British English? I think we'd need to look for the following:

`organizations`
`link.darkFiber`
`link.fiberType`
`link.fiberTypeDetails`
`link.fiberCount`
`link.fiberLength`

**Comment by duncandewhurst** [comment]
Tangentially related to https://github.com/Open-Telecoms-Data/open-fibre-data-standard/issues/133, we can consider including a check/warning for coordinates with too many decimal places since coordinates with more than 6 decimal places identify a location to an accuracy of 10cm or less, which is likely to be an artefact of the data pipeline rather than the accuracy to which the location was actually measured. The warning message could be something like:

> Your data includes coordinates with a precision greater than six decimal places, which is equivalent to an accuracy of ± 0.01m or less. You ought to check if this level of precision is an artefact of your data pipeline. If so, you ought to truncate coordinate data to reflect the accuracy to which your location data were actually measured.

**Comment by odscjames** [comment]
Can I request that anything new is put in an issue of it's own, and we'll keep this issue on the checklist that Duncan provides in the first comment?

See links below this comment for where things are moved to

**Comment by odscjames** [comment]
What about name only on link? 

```

 "phases": [
    {
      "id": "1"
    }
  ],
  "nodes": [
    {
      "id": "1",
      "phase": {
        "id": "1",
        "name": "NextGen Phase 1"
      }
  ]
```

Seems good to raise this, otherwise you could have inconsistent names used in different reference objects and if there is no name on the phase object that would never be caught.

**Comment by lgs85** [comment]
> What about the name only existing on the reference and not the phrase?

Yes, I think this is a sensible check to add in.

**Comment by duncandewhurst** [comment]
All sounds good!

**Comment by duncandewhurst** [comment]
Testing on 2022-11-08 with [this file](https://gist.github.com/duncandewhurst/43f4365607cd2aaa3d968da93f4757ad), CoVE fails to report the unresolvable node references.

**Comment by odscjames** [comment]
Identifier uniqueness checks - which of the 2 error boxes should these appear in? What should the content be?

**Comment by duncandewhurst** [comment]
Let's put it in the additional checks box for now to maintain the separation between JSON Schema validation errors and additional checks. Whether that distinction is important to users or not can be a topic for later :-)

I've added these checks to the [additional checks spreadsheet](https://docs.google.com/spreadsheets/d/19H7a53wKqsb-AGYmygeHlnIIavgB88Pds52_Ar1kHMM/edit#gid=0) and specified the error titles, descriptions and result table columns there.

**Comment by odscjames** [comment]
> Whether that distinction is important to users or not can be a topic for later :-)

Yes, I really want to have that chat. It's always seemed weird to me.

Technically, in the past we have solved this with a custom JSON Schema validator so technically we can do either - but users shouldn't have to care about that kind of thing ....

One additional check coming right up

**Comment by odscjames** [comment]
Ready for testing on live

**Comment by duncandewhurst** [comment]
Looks good! I've added https://github.com/Open-Telecoms-Data/lib-cove-ofds/issues/28 to the project board so I'll close this issue.
