### ISSUE TITLE
Make sure flatten tool options set correctly

### ISSUE THREAD

**Issue by odscjames** [Open-Telecoms-Data/lib-cove-ofds#10]
Things like root_list_path are wrong

Some WIP on https://github.com/Open-Telecoms-Data/lib-cove-ofds/commits/config

**Comment by duncandewhurst** [comment]
The Flatten Tool options we're using are here: https://github.com/Open-Telecoms-Data/open-fibre-data-standard/issues/107

**Comment by odscjames** [comment]
On 2022-11-08

**Comment by duncandewhurst** [comment]
Looks good, notwithstanding https://github.com/Open-Telecoms-Data/cove-ofds/issues/3#issuecomment-1307932890

**Comment by odscjames** [comment]
ready to test on live

**Comment by duncandewhurst** [comment]
Looks good! I'll close this issue in favour of https://github.com/Open-Telecoms-Data/cove-ofds/issues/3
