### ISSUE TITLE
Checks - Links array has one and only one describedby value, value is correct

### ISSUE THREAD

**Issue by odscjames** [Open-Telecoms-Data/lib-cove-ofds#13]
https://json-schema.org/understanding-json-schema/reference/array.html#contains will only do some of these checks

**Comment by duncandewhurst** [comment]
I think that we can handle this in the schema without needing an additional check by using [tuple validation](https://json-schema.org/understanding-json-schema/reference/array.html#id7) and [items](https://json-schema.org/understanding-json-schema/reference/array.html#items), e.g.

```json
{
    "links": {
      "type": "array",
      "prefixItems": [
        {
          "type": "object",
          "properties": {
            "href": {
              "type": "string",
              "const": "https://raw.githubusercontent.com/Open-Telecoms-Data/open-fibre-data-standard/0__1__0__beta/schema/network-schema.json"
            },
            "rel": {
              "type": "string",
              "const": "describedby"
            }
          }
        }
      ],
      "items": {
        "$ref": "#/definitions/Link"
      },
      "minItems": 1,
      "uniqueItems": true
    }
}
```

The only downside that I can see is that would mean that the `describedby` link would always need to be the first item in the `links` array. I don't think that's too much of an extra problem for implementers.

Does that sound good? If so I'll update https://github.com/Open-Telecoms-Data/open-fibre-data-standard/pull/157

**Comment by odscjames** [comment]
Think that is good

**Comment by duncandewhurst** [comment]
Closing as this is now handled by schema validation.
