### ISSUE TITLE
Update documentation URLs to point to /latest/ 

### ISSUE THREAD

**Issue by duncandewhurst** [Open-Telecoms-Data/lib-cove-ofds#32]
Currently, most URLs point to `0.1-dev` because some of the docs have been rearranged for the beta. Once we make a beta release, we should update the URLs to point to `latest`

**Comment by duncandewhurst** [comment]
Beta release PR: https://github.com/Open-Telecoms-Data/open-fibre-data-standard/pull/181

**Comment by odscjames** [comment]
This should just be updating https://github.com/Open-Telecoms-Data/lib-cove-ofds/blob/main/libcoveofds/schema.py#L9

**Comment by lgs85** [comment]
>However there is the schema files used - will this need an update?

Yes it will - if we use:

https://raw.githubusercontent.com/Open-Telecoms-Data/open-fibre-data-standard/0__1__0__beta/schema/network-schema.json
https://raw.githubusercontent.com/Open-Telecoms-Data/open-fibre-data-standard/0__1__0__beta/schema/network-package-schema.json

Then we can continue to make changes to the schema on the `0.1-dev` branch without affecting cove.

**Comment by odscjames** [comment]
I see 0__1__0__beta is a tag so I'll just use that (Normally we lock the schema files used in the library to a specific commit to ensure stability - we wouldn't want to use a branch name.)

https://github.com/Open-Telecoms-Data/open-fibre-data-standard/compare/b4dbea4705039610d893c12e688fd2a1f9b877ca...0__1__0__beta says there are no actual schema changes between the last used version and this one, so it's not urgent to release onto cove.

**Comment by odscjames** [comment]
Now merged to main - if you agree it's not urgent to release onto cove @lgs85 you could close this issue.

**Comment by lgs85** [comment]
Yes that's fine

**Comment by duncandewhurst** [comment]
Thanks, both!
