### ISSUE TITLE
python checks: data cleaning

### ISSUE THREAD

**Issue by ghost** [Open-Telecoms-Data/lib-cove-ofds#36]
Uploading https://github.com/Open-Telecoms-Data/lib-cove-ofds/blob/main/tests/fixtures/jsonschemavalidate/basic_1.input.json to cove crashes it.

```
class NodesLocationAndSpansRouteAdditionalCheckForNetwork(AdditionalCheckForNetwork):
    def check_node_first_pass(self, node: dict):
        location = node.get("location")
        if location:
            type = location.get("type")
```

`'str' object has no attribute 'get'`

**Comment by odscjames** [comment]
On live - I've tested - as I reported I'm going to close
