### ISSUE TITLE
List additional fields and provide guidance to users

### ISSUE THREAD

**Issue by odscjames** [Open-Telecoms-Data/lib-cove-ofds#4]
From https://github.com/Open-Telecoms-Data/lib-cove-ofds/issues/1#issuecomment-1280888386 

Based on [this comment](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/issues/54#issuecomment-1280840403), could we look for fields with American spellings and include a friendly error message stating that the standard uses British English? I think we'd need to look for the following:

`organizations`
`link.darkFiber`
`link.fiberType`
`link.fiberTypeDetails`
`link.fiberCount`
`link.fiberLength`

**Comment by odscjames** [comment]
Some of our Cove's list additional fields anyway, is the first step here to make sure that works well?

If we want to go further and highlight other spellings, one question is where would this data come from? Could the standard have a list of them somewhere, so that 

* other tools can use it
* the data in the list is updated as the standard is

Can we try and change the data to the correct fields, so we can do even more useful checks? eg "You've used organizations not organisations. Additionally, we corrected that for you and we found you were using the country field wrong." (worded better, obvs)

**Comment by lgs85** [comment]
> Some of our Cove's list additional fields anyway, is the first step here to make sure that works well?

Yes, I think so

> If we want to go further and highlight other spellings, one question is where would this data come from? Could the standard have a list of them somewhere, so that
> 
> * other tools can use it
> * the data in the list is updated as the standard is

We could, but intuitively this feels like overkill. I wonder if step 1 above is sufficient?


> Can we try and change the data to the correct fields, so we can do even more useful checks? eg "You've used organizations not organisations. Additionally, we corrected that for you and we found you were using the country field wrong." (worded better, obvs)

Again my intuition is that we can just flag additional fields for now, especially given that decisions on language may change in the medium term. I don't have especially strong views either way though.

**Comment by duncandewhurst** [comment]
I think that listing additional fields with the following message is sufficient for now:

> Your data contains additional fields that are not part of the standard. You should check that additional fields are not the result of typos in field names or other errors in your mapping or data pipeline. You should document the structure, format and meaning of additional fields in your [data user guide](https://open-fibre-data-standard.readthedocs.io/en/latest/guidance/publication.html#how-to-write-a-data-user-guide).

**Comment by duncandewhurst** [comment]
I've renamed the issue to reflect what needs to be done.

**Comment by duncandewhurst** [comment]
Closing in favour of https://github.com/Open-Telecoms-Data/cove-ofds/issues/20
