### ISSUE TITLE
Support for multiple network providers

### ISSUE THREAD

**Issue by duncandewhurst** [Open-Telecoms-Data/lib-cove-ofds#64]
https://github.com/Open-Telecoms-Data/open-fibre-data-standard/pull/234 makes the following changes to the schema:

* Replace `Node.networkProvider` (an `OrganisationReference` object) with `Node.networkProviders` (an array of `OrganisationReference` objects)
* Replace` Span.networkProvider` (an `OrganisationReference` object) with `Span.networkProviders` (an array of `OrganisationReference` objects)

The following checks need updating to reflect the changes:

* [Organisation reference is resolvable](https://libcoveofds.readthedocs.io/en/latest/checks.html#organisation-reference-is-resolvable)
* [Organisation name is consistent](https://libcoveofds.readthedocs.io/en/latest/checks.html#organisation-reference-name-is-consistent)

The [JSONToGeoJSONConverter](https://libcoveofds.readthedocs.io/en/latest/api.html#jsontogeojsonconverter) and [GeoJSONToJSONConverter](https://libcoveofds.readthedocs.io/en/latest/api.html#geojsontojsonconverter) also needs updating for the equivalent changes to the GeoJSON publication format:

* `nodes.geojson`: `features/properties/networkProvider` (object) -> `features/properties/networkProviders` (array)
* `spans.geojson`: `features/properties/networkProvider` (object) -> `features/properties/networkProviders` (array)

The changes are not yet released, but you can use the schema and example files from [`0.2-dev`](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/tree/0.2-dev) for development and testing.

**Comment by odscjames** [comment]
Now all in library and released
