### ISSUE TITLE
GeoJSON conversion: Add featureType field

### ISSUE THREAD

**Issue by duncandewhurst** [Open-Telecoms-Data/lib-cove-ofds#73]
Related to https://github.com/Open-Telecoms-Data/cove-ofds/issues/96, the task is to implement the `featureType` field added in https://github.com/Open-Telecoms-Data/open-fibre-data-standard/pull/266.

**Comment by odscjames** [comment]
Done well this will also sweep up https://github.com/Open-Telecoms-Data/lib-cove-ofds/issues/21

**Comment by odscjames** [comment]
Think can close, now released here and in Cove
