### ISSUE TITLE
Documentation of additional checks

### ISSUE THREAD

**Issue by duncandewhurst** [Open-Telecoms-Data/lib-cove-ofds#8]
Please can we document a list of additional checks that we can use as a reference and to track which are implemented in code and which are suggestions for the future etc.

We can perhaps combine this with the list of error and warning messages requested in https://github.com/Open-Telecoms-Data/cove-ofds/issues/4

**Comment by odscjames** [comment]
First go at this will appear at https://libcoveofds.readthedocs.io/en/latest/ when #6  is merged.

Note: The main docs site here will track when code is merged to main branch. But a new version of this library has to be released and that put into cove before the functionality is actually live in the web app! We can think of ways to improve tracking this if that's an issue - probably a docs page that tells people how to check the above things.

**Comment by duncandewhurst** [comment]
Great. Thanks!

With an eye on easing maintenance going forward, would it be possible to link these somehow to the source code for each check?

I'm thinking something like OCDS Kit's approach of putting the docs in the code as docstrings and then building the documentation from that could be useful: https://ocdskit.readthedocs.io/en/latest/api/combine.html#ocdskit.combine.package_records

**Comment by odscjames** [comment]
https://libcoveofds.readthedocs.io/en/latest/additional_checks.html is up

> putting the docs in the code as docstrings

Possibly - there may not be a  1-to-1 mapping of python functions/classes to headings that people would actually want in docs but I'll have a think.

**Comment by odscjames** [comment]
> Note: The main docs site here will track when code is merged to main branch. But a new version of this library has to be released and that put into cove before the functionality is actually live in the web app! We can think of ways to improve tracking this if that's an issue - probably a docs page that tells people how to check the above things.

I can do this now tho.

**Comment by duncandewhurst** [comment]
I've put together a [spreadsheet](https://docs.google.com/spreadsheets/d/19H7a53wKqsb-AGYmygeHlnIIavgB88Pds52_Ar1kHMM/edit?usp=sharing) with the additional checks listed on https://libcoveofds.readthedocs.io/en/latest/additional_checks.html. For each check, I've documented the following:

* Name
* Description
* Scope (Field or Network)
* Type (Conformance, Reference, Coherence, Consistency, Value, Type and Information)
* Failure severity (Information, Warning, Error)
* Field paths the check applies to
* Feedback title, i.e. the heading to show in the CoVE interface if there is a failure
* Feedback description, i.e. the text to show in the CoVE interface if there is a failure

Based on this, we can generate a documentation page, excluding the latter two points, which are relevant to https://github.com/Open-Telecoms-Data/cove-ofds/issues/4.

@odscjames please could you check that you're happy with this? Thinking about having an SSOT and generating documentation, how much of the above would be feasible to document in code or would it be better to maintain the spreadsheet as the SSOT?

@lgs85 please could you cast your eye over the check descriptions, feedback title and feedback descriptions and check that you're happy with them? Thanks!

**Comment by odscjames** [comment]
I wonder if we need a split here; remember the library outputs JSON structures with information on the error and Cove turns it into human readable messages. This is deliberate - other tools in the future may want different UI's and take other approaches.

In the library, do we need to update https://libcoveofds.readthedocs.io/en/latest/python_validate.html to include more info on each check, including what data structure it outputs for each check? And if we could find a way to pull this from code, this would be ideal as it would make the docs easier to keep up to date.

In cove, do we need more documentation? https://github.com/Open-Telecoms-Data/cove-ofds/blob/live/cove_ofds/templates/cove_ofds/additional_checks_table.html is the SSOT here, and it has basic enough Python I would hope many people could edit it.

**Comment by duncandewhurst** [comment]
Closed by https://github.com/Open-Telecoms-Data/lib-cove-ofds/pull/57
